// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PaymentAPI.Data;

namespace PaymentAPI.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    partial class ApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.10");

            modelBuilder.Entity("PaymentAPI.Models.PaymentDetails", b =>
                {
                    b.Property<int>("paymentDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("cardNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("cardOwnerName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("expirationDate")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("securityCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("paymentDetailId");

                    b.ToTable("PaymentDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
